export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_SUCCESS_REQUEST = "USER_SUCCESS_REQUEST";
export const USER_FAIL_REQUEST = "USER_FAIL_REQUEST";
